// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stock struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Name         string
	Symbol       string
	Customsymbol string
	Scripttype   string
	Industry     pgtype.Text
	Isin         pgtype.Text
	Fno          bool
}
