// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type Stock struct {
	ID           int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Name         string
	Symbol       string
	Customsymbol string
	Scripttype   string
	Industry     string
	Isin         string
	Fno          bool
}
