// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Daily struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Stockid   pgtype.UUID
	Open      pgtype.Numeric
	High      pgtype.Numeric
	Low       pgtype.Numeric
	Close     pgtype.Numeric
	Adjclose  pgtype.Numeric
	Volume    pgtype.Int4
	Timestamp pgtype.Timestamp
}

type Stock struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Name         string
	Symbol       string
	Customsymbol string
	Scripttype   string
	Industry     pgtype.Text
	Isin         pgtype.Text
	Fno          bool
}
